# This file contains values from Cookiecutter

default_context:
  project_name: "spaghettis"
  repo_name: "hackacity2022"
  description: "A short description of the project. No quotes."
  organization: "Fraunhofer Spaghettis"
  license: "No license"
  organization_email: "no-reply@fraunhofer.pt"
  line_length: "120"
  python_minimal_version: "3.10"
